# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       kf5-kio
Summary:    KDE Frameworks 5 Tier 3 solution for filesystem abstraction
Version:    4.99.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kf5-kio.yaml
Source101:  kf5-kio-rpmlintrc
Requires:   kf5-filesystem
Requires:   kf5-kwallet-libs
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kf5-karchive-devel
BuildRequires:  kf5-kbookmarks-devel
BuildRequires:  kf5-kcodecs-devel
BuildRequires:  kf5-kcompletion-devel
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-kconfigwidgets-devel
BuildRequires:  kf5-kcoreaddons-devel
BuildRequires:  kf5-kdbusaddons-devel
BuildRequires:  kf5-kdoctools-devel
BuildRequires:  kf5-ki18n-devel
BuildRequires:  kf5-kiconthemes-devel
BuildRequires:  kf5-kitemviews-devel
BuildRequires:  kf5-kjobwidgets-devel
BuildRequires:  kf5-knotifications-devel
BuildRequires:  kf5-kservice-devel
BuildRequires:  kf5-solid-devel
BuildRequires:  kf5-kwidgetsaddons-devel
BuildRequires:  kf5-kwindowsystem-devel
BuildRequires:  kf5-kxmlgui-devel
BuildRequires:  kf5-kwallet-devel
BuildRequires:  libxml2-devel
BuildRequires:  libxslt-devel
BuildRequires:  zlib-devel


%description
KDE Frameworks 5 Tier 3 solution for filesystem abstraction



%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kf5-karchive-devel
Requires:   kf5-kbookmarks-devel
Requires:   kf5-kcodecs-devel
Requires:   kf5-kcompletion-devel
Requires:   kf5-kconfig-devel
Requires:   kf5-kconfigwidgets-devel
Requires:   kf5-kcoreaddons-devel
Requires:   kf5-kdbusaddons-devel
Requires:   kf5-kdoctools-devel
Requires:   kf5-ki18n-devel
Requires:   kf5-kiconthemes-devel
Requires:   kf5-kitemviews-devel
Requires:   kf5-kjobwidgets-devel
Requires:   kf5-knotifications-devel
Requires:   kf5-kservice-devel
Requires:   kf5-solid-devel
Requires:   kf5-kwidgetsaddons-devel
Requires:   kf5-kwindowsystem-devel
Requires:   kf5-kxmlgui-devel
Requires:   kf5-kwallet-devel

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%package doc
Summary:    Documentation files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kf5-kio%{?_isa} = %{version}-%{release}

%description doc
Documentation files for %{name}.



%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post












%files
%defattr(-,root,root,-)
%doc COPYING.LIB README.md
%{_kf5_libdir}/*.so.*
%{_kf5_bindir}/ktelnetservice5
%{_kf5_bindir}/kcookiejar5
%{_kf5_bindir}/kmailservice5
%{_kf5_sysconfdir}/xdg/*
%{_kf5_qtplugindir}/kf5/*
%{_kf5_libexecdir}/kio_http_cache_cleaner
%{_kf5_libexecdir}/kioexec
%{_kf5_libexecdir}/kpac_dhcp_helper
%{_kf5_libexecdir}/kioslave
%{_kf5_datadir}/applications/*.desktop
%{_kf5_datadir}/dbus-1/interfaces/*.xml
%{_kf5_datadir}/kservices5/*
%{_kf5_datadir}/kservicetypes5/*
%{_kf5_datadir}/knotifications5/proxyscout.*
%{_kf5_datadir}/kf5/kcookiejar/domain_info
# >> files
# << files


%files devel
%defattr(-,root,root,-)
%{_kf5_includedir}/*
%{_kf5_libdir}/*.so
%{_kf5_libdir}/cmake/KF5KIO
%{_datadir}/qt5/mkspecs/modules/*.pri
# >> files devel
# << files devel

%files doc
%defattr(-,root,root,-)
%{_kf5_mandir}/man8/*
%{_kf5_datadir}/doc/HTML/en/kioslave5/
# >> files doc
# << files doc

