# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kio

# >> macros
# << macros

Summary:    KDE Frameworks 5 Tier 3 solution for filesystem abstraction
Version:    5.3.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kio.yaml
Source101:  kio-rpmlintrc
Requires:   kf5-filesystem
Requires:   kwallet-libs
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(libxslt)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  karchive-devel
BuildRequires:  kbookmarks-devel
BuildRequires:  kcodecs-devel
BuildRequires:  kcompletion-devel
BuildRequires:  kconfig-devel
BuildRequires:  kconfigwidgets-devel
BuildRequires:  kcoreaddons-devel
BuildRequires:  kdbusaddons-devel
BuildRequires:  kdoctools-devel
BuildRequires:  ki18n-devel
BuildRequires:  kiconthemes-devel
BuildRequires:  kitemviews-devel
BuildRequires:  kjobwidgets-devel
BuildRequires:  knotifications-devel
BuildRequires:  kservice-devel
BuildRequires:  solid-devel
BuildRequires:  kwidgetsaddons-devel
BuildRequires:  kwindowsystem-devel
BuildRequires:  kxmlgui-devel
BuildRequires:  kwallet-devel
BuildRequires:  libacl-devel

%description
KDE Frameworks 5 Tier 3 solution for filesystem abstraction


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   karchive-devel
Requires:   kbookmarks-devel
Requires:   kcodecs-devel
Requires:   kcompletion-devel
Requires:   kconfig-devel
Requires:   kconfigwidgets-devel
Requires:   kcoreaddons-devel
Requires:   kdbusaddons-devel
Requires:   kdoctools-devel
Requires:   ki18n-devel
Requires:   kiconthemes-devel
Requires:   kitemviews-devel
Requires:   kjobwidgets-devel
Requires:   knotifications-devel
Requires:   kservice-devel
Requires:   solid-devel
Requires:   kwidgetsaddons-devel
Requires:   kwindowsystem-devel
Requires:   kxmlgui-devel
Requires:   kwallet-devel
Requires:   libacl-devel

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%package doc
Summary:    Documentation files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kio%{?_isa} = %{version}-%{release}

%description doc
Documentation files for %{name}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING.LIB README.md
%{_kf5_libdir}/*.so.*
%{_kf5_bindir}/ktelnetservice5
%{_kf5_bindir}/kcookiejar5
%{_kf5_bindir}/kmailservice5
%{_kf5_configdir}/*
%{_kf5_plugindir}/*
%{_kf5_libexecdir}/kio_http_cache_cleaner
%{_kf5_libexecdir}/kioexec
%{_kf5_libexecdir}/kpac_dhcp_helper
%{_kf5_libexecdir}/kioslave
%{_kf5_sharedir}/applications/*.desktop
%{_kf5_dbusinterfacesdir}/*.xml
%{_kf5_servicesdir}/*
%{_kf5_servicetypesdir}/*
%{_kf5_sharedir}/knotifications5/proxyscout.*
%{_kf5_datadir}/kcookiejar/domain_info
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kf5_includedir}/*
%{_kf5_libdir}/*.so
%{_kf5_cmakedir}/KF5KIO
%{_kf5_mkspecsdir}/*.pri
# >> files devel
# << files devel

%files doc
%defattr(-,root,root,-)
%{_mandir}/man8/*
%{_kf5_htmldir}/en/kioslave5/
# >> files doc
# << files doc
